name: Build and Test Pipeline - Sukhman Aulakh

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Starting build process
        run: echo "Starting build process..."

      - name: Simulate compilation
        run: sleep 3

      - name: Build completed
        run: echo "Build completed successfully"

      - name: Built by
        run: echo "Built by Sukhman Aulakh"

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Running automated tests
        run: echo "Running automated tests..."

      - name: Simulate tests
        run: sleep 2

      - name: Print date and time
        run: date

      - name: All tests passed
        run: echo "All tests passed for Sukhman Aulakh"
